flags: {}
packages:
- '.'
extra-deps:
- blaze-html-0.8.1.3
- blaze-markup-0.7.1.1
- digestive-functors-0.8.2.0
- digestive-functors-blaze-0.6.1.0
- digestive-functors-scotty-0.2.0.2
- HPDF-1.4.7
- heroku-0.1.2.3
resolver: lts-9.6
